######### Input file #############
# Units in normalized units
##################################
# Choose of potential mode
central=1 
# 1 = mass anomaly/crater ; 2 = ellipsoid
distribution=2
# 1 = uniform; 2 = random
# Setting central object (in SI)
# mass of central sphere in kg
M1=1.13e20
M2=2.75e17
# density in kg/m**3
p=0.72e3 
# spin period in hour
Trot=7.44 
# mass ratio (positive - crater)
#alpha=0.002  
alpha=0.002       
J2=0.1
C22=0.0
##################################
# Simulation parameters (in normalized units)
# initial radius
a_init=1.
# final radius 
a_end=3.5

e_init=1e-4
e_end=0.7

varpi = 30.0
# varpi em graus
# Exemplo de como você pode configurar o input.ini para definir valores específicos para x_iniciais
#x_iniciais= 8.47564, 8.5556, 8.98793, 9.2604, 9.21858
# number of particles
Npart=20
# number of orbits
Norb=500
# Jacobi constant
#Cj=1.961
# ejection ratio
rejec= 100.
# save the xy_* file? 0 - no / 1 - yes
save_xy=0